---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__modify_built-in_schedules.html 
keywords:  
summary: Per modificare le pianificazioni incorporate per i processi del client VMware vSphere utilizzando il plug-in SnapCenter per le API REST di VMware vSphere, è necessario seguire la sequenza prescritta di chiamate API REST. 
---
= Workflow API REST per modificare le pianificazioni integrate
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per modificare le pianificazioni incorporate per i processi del client VMware vSphere utilizzando il plug-in SnapCenter per le API REST di VMware vSphere, è necessario seguire la sequenza prescritta di chiamate API REST.

Le pianificazioni integrate sono le pianificazioni fornite come parte del prodotto; ad esempio, la pianificazione di dump del database MySQL. È possibile modificare i seguenti programmi:
`Schedule-DatabaseDump`
`Schedule-PurgeBackups`
`Schedule-AsupDataCollection`
`Schedule-ComputeStorageSaving`
`Schedule-PurgeJobs`

Per ogni API REST, aggiungere `\https://<server>:<port>` alla parte anteriore dell'API REST per formare un endpoint completo.

|===
| Fase | API REST | Commenti 


| 1 | `/4.1/schedules` | `Get all built-in` pianifica ottiene un elenco delle pianificazioni dei lavori fornite originariamente nel prodotto. Prendere nota del nome del programma che si desidera modificare e dell'espressione cron associata. 


| 2 | `/4.1/schedules` | `Modify any built-in schedule` modifica la pianificazione denominata. Passare il nome del programma dal passaggio 1 e creare una nuova espressione cron per il programma. 
|===